# _config.yml

remote_theme: "mmistakes/minimal-mistakes"
locale: "en-US"
title: "Nathan Quiblier"
email: "nathan.quiblier@gmail.com"
description: >-
  Postdoctoral researcher in computational biology and applied mathematics.
url: "https://nathanqblr.github.io"
baseurl: ""

logo: "/ressources/photo_cv_last.jpg"

author:
  name: "Nathan Quiblier"
  avatar: "/ressources/photo_cv_last.jpg"
  bio: "Postdoc in applied mathematics & computational biology"
  location: "Paris, France"
  email: "nathan.quiblier@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/NathanQblr"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/nathan-quiblier/"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=TyQ2D7wAAAAJ&hl=fr"
    - label: "FranÃ§ais ðŸ‡«ðŸ‡·"
      icon: "fas fa-language"
      url: "/fr/"

# French author config for /fr/ pages
collections:
  fr:
    output: true
    permalink: /fr/:path/

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        sticky: true

  - scope:
      path: "fr"
    values:
      author:
        name: "Nathan Quiblier"
        avatar: "/assets/images/portrait.jpg"
        bio: "Chercheur postdoctoral en modÃ©lisation mathÃ©matique appliquÃ©e Ã  la biologie"
        location: "Paris, France"
        email: "nathan.quiblier@gmail.com"
        links:
          - label: "GitHub"
            icon: "fab fa-github"
            url: "https://github.com/NathanQblr"
          - label: "LinkedIn"
            icon: "fab fa-linkedin"
            url: "https://www.linkedin.com/in/nathan-quiblier/"
          - label: "Google Scholar"
            icon: "ai ai-google-scholar"
            url: "https://scholar.google.com/citations?user=TyQ2D7wAAAAJ&hl=fr"
          - label: "English ðŸ‡¬ðŸ‡§"
            icon: "fas fa-language"
            url: "/"
      header:
        nav:
          - title: "Nathan Quiblier"
            url: "/fr/"
          - title: "Publications"
            url: "/fr/publications/"
          - title: "Projets"
            url: "/fr/projects/"
          - title: "Enseignement"
            url: "/fr/teaching/"
          - title: "PrÃ©sentations"
            url: "/fr/talks/"
          - title: "Recherche"
            url: "/fr/research/"
          - title: "CV"
            url: "/fr/cv/"
          - title: "English ðŸ‡¬ðŸ‡§"
            url: "/"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

include:
  - _pages

# navigation
header:
  nav:
    - title: "Nathan Quiblier"
      url: "/"
    - title: "Publications"
      url: "/publications/"
    - title: "Projects"
      url: "/projects/"
    - title: "Teaching"
      url: "/teaching/"
    - title: "Talks"
      url: "/talks/"
    - title: "Research"
      url: "/research/"
    - title: "CV"
      url: "/cv/"
    - title: "FranÃ§ais ðŸ‡«ðŸ‡·"
      url: "/fr/"
