remote_theme: "mmistakes/minimal-mistakes"
locale: "en-US"
title: "Nathan Quiblier"
email: "nathan.quiblier@gmail.com"
description: >-
  Postdoctoral researcher in computational biology and applied mathematics.
url: "https://nathanqblr.github.io"
baseurl: ""

author:
  name: "Nathan Quiblier"
  avatar: "/ressources/photo_cv_last.jpg"
  bio: "Postdoctoral researcher in applied mathematics & computational biology"
  location: "Paris, France"
  email: "nathan.quiblier@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/NathanQblr"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/nathan-quiblier/"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=TyQ2D7wAAAAJ&hl=fr"

# French author config for /fr/ pages
collections:
  fr:
    output: true
    permalink: /fr/:path/

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: "main"
        sticky: true
        custom:
          - image: "/ressources/photo_cv_last.jpg"
            image_alt: "Nathan Quiblier"
            text: |
              **Nathan Quiblier**  
              Postdoctoral researcher in applied mathematics & computational biology  
              ğŸ“ Paris, France  
              âœ‰ï¸ [nathan.quiblier@gmail.com](mailto:nathan.quiblier@gmail.com)  
              ğŸ”— [GitHub](https://github.com/NathanQblr)  
              ğŸ”— [LinkedIn](https://www.linkedin.com/in/nathan-quiblier/)  
              ğŸ”— [Google Scholar](https://scholar.google.com/citations?user=TyQ2D7wAAAAJ&hl=fr)
  - scope:
      path: "fr"
    values:
      sidebar:
        nav: "main"
        sticky: true
        custom:
          - image: "/ressources/photo_cv_last.jpg"
            image_alt: "Nathan Quiblier"
            text: |
              **Nathan Quiblier**  
              Chercheur postdoctoral en mathÃ©matiques appliquÃ©es Ã  la biologie  
              ğŸ“ Paris  
              âœ‰ï¸ [nathan.quiblier@gmail.com](mailto:nathan.quiblier@gmail.com)  
              ğŸ”— [GitHub](https://github.com/NathanQblr)  
              ğŸ”— [LinkedIn](https://www.linkedin.com/in/nathan-quiblier/)  
              ğŸ”— [Google Scholar](https://scholar.google.com/citations?user=TyQ2D7wAAAAJ&hl=fr)


plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

include:
  - _pages
